baseURL = "https://effective-flow.ch/"
languageCode = "en-us"
title = "Effective Flow"
enableRobotsTXT = true

[params]
  companyName = "Effective Flow"
  description = "Software and consulting for people who teach and explain."
  productSiteUrl = "https://2reflect.effective-flow.com"

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menus.main]]
    name = "Blog"
    pageRef = "/blog"
    weight = 20

  [[menus.main]]
    name = "Contact"
    pageRef = "/contact"
    weight = 30

  [[menus.main]]
    name = "2Reflect"
    url = "https://2reflect.effective-flow.com"
    weight = 40
    [menus.main.params]
      external = true
